### ISSUE TITLE
Pidgin-whatsap:Unable to compile on Linxu Ubuntu 20.04

### ISSUE THREAD

**Issue by Capsis** [hoehermann/purple-gowhatsapp#86]
491707802092@s.whatsapp.net

Dear community,

Till now I have been using the whatsapp plugin for pidgin and am grateful for it.
To make it even better I am raising three different issues in three tickets:

This is the third issue.
Actually I am not able to use Whatsapp since two days because of issue 2.
I am on Ubuntu 20.04 with 64 bit

Compiling it I needed to install go by doing
sudo apt  install gccgo-go
(If there are any errors one shoudl do apt --fix-broken install)
make

Upon this I get multiple first defined here errors in basically all lines of gwa-to-purple and constants.h

```
/home/business/Desktop/purple-gowhatsapp-master/gwa-to-purple.c:12: multiple definition of `gowhatsapp_process_message_bridge'; gwa-to-purple.o:/home/business/Desktop/purple-gowhatsapp-master/gwa-to-purple.c:12: first defined here

/usr/bin/ld: gwa-to-purple.o:/home/business/Desktop/purple-gowhatsapp-master/constants.h:45: multiple definition of `GOWHATSAPP_SESSION_WID_KEY'; gwa-to-purple.o:/home/business/Desktop/purple-gowhatsapp-master/constants.h:45: first defined here
```
at the end make: *** [Makefile:55: purplegwa.a] Error 2

Uncommenting those lines throws other errors

```
/usr/include/glib-2.0/gobject/gparam.h:271:8: note: declared here
/usr/include/libpurple/media.h:214:3: warning: ‘GParameter’ is deprecated [-Wdeprecated-declarations]
usr/include/libpurple/media.h:165:3: warning: ‘GParameter’ is deprecated [-Wdeprecated-declarations]
  165 |   guint num_params, GParameter *params);
/usr/include/libpurple/media/../util.h:1397:13: warning: Deprecated pre-processor symbol, replace with 
 1397 | G_CONST_RETURN gchar *purple_gai_strerror(gint errnum);

libgowhatsapp.c:149:70: error: ‘GOWHATSAPP_GET_ICONS_OPTION’ undeclared (first use in this function)
  149 |         if (purple_account_get_bool(purple_buddy_get_account(buddy), GOWHATSAPP_GET_ICONS_OPTION, FALSE)) {
      |                                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~
libgowhatsapp.c:149:70: note: each undeclared identifier is reported only once for each function it appears in
libgowhatsapp.c: In function ‘gowhatsapp_assume_buddy_online’:
libgowhatsapp.c:169:42: error: ‘GOWHATSAPP_FAKE_ONLINE_OPTION’ undeclared (first use in this function)
  169 |     if (purple_account_get_bool(account, GOWHATSAPP_FAKE_ONLINE_OPTION, TRUE)) {
      |                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
libgowhatsapp.c: In function ‘gowhatsapp_message_newer_than_last_session’:
libgowhatsapp.c:210:46: error: ‘GOWHATSAPP_PREVIOUS_SESSION_TIMESTAMP_KEY’ undeclared (first use in this function)
  210 |         purple_account_set_int(gwa->account, GOWHATSAPP_PREVIOUS_SESSION_TIMESTAMP_KEY, ts); // TODO: find out if this narrowing of time_t aka. long int to int imposes a problem
      |                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
libgowhatsapp.c: In function ‘gowhatsapp_append_message_id_if_not_exists’:
libgowhatsapp.c:237:93: error: ‘GOWHATSAPP_MESSAGE_ID_STORE_SIZE_OPTION’ undeclared (first use in this function); did you mean ‘GOWHATSAPP_MESSAGEIDSTORE_SIZE’?
  237 |         const unsigned int GOWHATSAPP_MESSAGEIDSTORE_SIZE = purple_account_get_int(account, GOWHATSAPP_MESSAGE_ID_STORE_SIZE_OPTION, 1000);
      |                                                                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                             GOWHATSAPP_MESSAGEIDSTORE_SIZE
libgowhatsapp.c: In function ‘gowhatsapp_refresh_contactlist’:
libgowhatsapp.c:274:48: error: ‘GOWHATSAPP_FETCH_CONTACTS_OPTION’ undeclared (first use in this function)
  274 |     if (!purple_account_get_bool(gwa->account, GOWHATSAPP_FETCH_CONTACTS_OPTION, TRUE)) {
      |                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
libgowhatsapp.c: In function ‘gowhatsapp_display_message’:
libgowhatsapp.c:318:66: error: ‘GOWHATSAPP_SYSTEM_MESSAGES_ARE_ORDINARY_MESSAGES_OPTION’ undeclared (first use in this function)
  318 |     if (gwamsg->system && !purple_account_get_bool(gwa->account, GOWHATSAPP_SYSTEM_MESSAGES_ARE_ORDINARY_MESSAGES_OPTION, FALSE)) {
      |                                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
libgowhatsapp.c:322:73: error: ‘GOWHATSAPP_TIMESTAMP_FILTERING_OPTION’ undeclared (first use in this function)
  322 |     gboolean check_message_date = purple_account_get_bool(gwa->account, GOWHATSAPP_TIMESTAMP_FILTERING_OPTION, FALSE);
      |                                                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
libgowhatsapp.c: In function ‘gowhatsapp_process_message’:
libgowhatsapp.c:440:48: error: ‘GOWHATSAPP_SESSION_CLIENDID_KEY’ undeclared (first use in this function)
  440 |             purple_account_set_string(account, GOWHATSAPP_SESSION_CLIENDID_KEY, gwamsg->clientId);
      |                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
libgowhatsapp.c:441:48: error: ‘GOWHATSAPP_SESSION_CLIENTTOKEN_KEY’ undeclared (first use in this function)
  441 |             purple_account_set_string(account, GOWHATSAPP_SESSION_CLIENTTOKEN_KEY, gwamsg->clientToken);
      |                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
libgowhatsapp.c:442:48: error: ‘GOWHATSAPP_SESSION_SERVERTOKEN_KEY’ undeclared (first use in this function)
  442 |             purple_account_set_string(account, GOWHATSAPP_SESSION_SERVERTOKEN_KEY, gwamsg->serverToken);
      |                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
libgowhatsapp.c:443:48: error: ‘GOWHATSAPP_SESSION_ENCKEY_KEY’ undeclared (first use in this function)
  443 |             purple_account_set_string(account, GOWHATSAPP_SESSION_ENCKEY_KEY, gwamsg->encKey_b64);
      |                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
libgowhatsapp.c:444:48: error: ‘GOWHATSAPP_SESSION_MACKEY_KEY’ undeclared (first use in this function)
  444 |             purple_account_set_string(account, GOWHATSAPP_SESSION_MACKEY_KEY, gwamsg->macKey_b64);
      |                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
libgowhatsapp.c:445:48: error: ‘GOWHATSAPP_SESSION_WID_KEY’ undeclared (first use in this function)
  445 |             purple_account_set_string(account, GOWHATSAPP_SESSION_WID_KEY, gwamsg->wid);
      |                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~
libgowhatsapp.c:450:54: error: ‘GOWHATSAPP_FAKE_ONLINE_OPTION’ undeclared (first use in this function)
  450 |                 if (purple_account_get_bool(account, GOWHATSAPP_FAKE_ONLINE_OPTION, TRUE)) {
      |                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
libgowhatsapp.c:457:50: error: ‘GOWHATSAPP_PLAIN_TEXT_LOGIN’ undeclared (first use in this function); did you mean ‘GOWHATSAPP_PLUGIN_VERSION’?
  457 |             if (purple_account_get_bool(account, GOWHATSAPP_PLAIN_TEXT_LOGIN, FALSE)) {
      |                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                  GOWHATSAPP_PLUGIN_VERSION
libgowhatsapp.c: In function ‘gowhatsapp_login’:
libgowhatsapp.c:506:86: error: ‘GOWHATSAPP_PREVIOUS_SESSION_TIMESTAMP_KEY’ undeclared (first use in this function)
  506 |     gwa->previous_sessions_last_messages_timestamp = purple_account_get_int(account, GOWHATSAPP_PREVIOUS_SESSION_TIMESTAMP_KEY, 0);
      |                                                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
libgowhatsapp.c:509:70: error: ‘GOWHATSAPP_RESTORE_SESSION_OPTION’ undeclared (first use in this function)
  509 |     gboolean restore_session = purple_account_get_bool(gwa->account, GOWHATSAPP_RESTORE_SESSION_OPTION, TRUE);
      |                                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
libgowhatsapp.c: In function ‘gowhatsapp_add_account_options’:
libgowhatsapp.c:641:17: error: ‘GOWHATSAPP_FAKE_ONLINE_OPTION’ undeclared (first use in this function)
  641 |                 GOWHATSAPP_FAKE_ONLINE_OPTION,
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
libgowhatsapp.c:648:17: error: ‘GOWHATSAPP_FETCH_CONTACTS_OPTION’ undeclared (first use in this function)
  648 |                 GOWHATSAPP_FETCH_CONTACTS_OPTION,
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
libgowhatsapp.c:656:17: error: ‘GOWHATSAPP_GET_ICONS_OPTION’ undeclared (first use in this function)
  656 |                 GOWHATSAPP_GET_ICONS_OPTION,
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~
libgowhatsapp.c:664:17: error: ‘GOWHATSAPP_MARK_READ_OPTION’ undeclared (first use in this function)
  664 |                 GOWHATSAPP_MARK_READ_OPTION,
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~
libgowhatsapp.c:671:17: error: ‘GOWHATSAPP_RESTORE_SESSION_OPTION’ undeclared (first use in this function)
  671 |                 GOWHATSAPP_RESTORE_SESSION_OPTION,
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
libgowhatsapp.c:678:17: error: ‘GOWHATSAPP_PLAIN_TEXT_LOGIN’ undeclared (first use in this function); did you mean ‘GOWHATSAPP_PLUGIN_VERSION’?
  678 |                 GOWHATSAPP_PLAIN_TEXT_LOGIN,
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                 GOWHATSAPP_PLUGIN_VERSION
libgowhatsapp.c:685:17: error: ‘GOWHATSAPP_MESSAGE_ID_STORE_SIZE_OPTION’ undeclared (first use in this function)
  685 |                 GOWHATSAPP_MESSAGE_ID_STORE_SIZE_OPTION,
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
libgowhatsapp.c:692:17: error: ‘GOWHATSAPP_TIMESTAMP_FILTERING_OPTION’ undeclared (first use in this function)
  692 |                 GOWHATSAPP_TIMESTAMP_FILTERING_OPTION,
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
libgowhatsapp.c:699:17: error: ‘GOWHATSAPP_SYSTEM_MESSAGES_ARE_ORDINARY_MESSAGES_OPTION’ undeclared (first use in this function)
  699 |                 GOWHATSAPP_SYSTEM_MESSAGES_ARE_ORDINARY_MESSAGES_OPTION,
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
libgowhatsapp.c:706:17: error: ‘GOWHATSAPP_DOWNLOAD_ATTACHMENTS_OPTION’ undeclared (first use in this function)
  706 |                 GOWHATSAPP_DOWNLOAD_ATTACHMENTS_OPTION,
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
libgowhatsapp.c:713:17: error: ‘GOWHATSAPP_DOWNLOAD_TRY_ONLY_ONCE_OPTION’ undeclared (first use in this function)
  713 |                 GOWHATSAPP_DOWNLOAD_TRY_ONLY_ONCE_OPTION,
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
libgowhatsapp.c:720:17: error: ‘GOWHATSAPP_INLINE_IMAGES_OPTION’ undeclared (first use in this function)
  720 |                 GOWHATSAPP_INLINE_IMAGES_OPTION,
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

leading to 
make: *** [Makefile:61: libgowhatsapp.so] Error 1

3. compilation error a.

**Comment by hoehermann** [comment]
Interesting. I am using "golang-go" instead of "gccgo-go". Can you try "golang-go" on the unmodified sources?

**Comment by hoehermann** [comment]
Closing due to lack of response.
